### 
POST http://localhost:4004/odata/v4/api_business_partner/A_BusinessPartner
Content-Type: application/json
Authorization: Basic bp-admin 123

{ "BusinessPartner": "TEST11",
 "BusinessPartnerIsBlocked": false,
 "to_BusinessPartnerAddress": [{"BusinessPartner": "TEST11",
 "AddressID": "HALLO",
 "HouseNumber": "2",
 "CityName": "Munich",
 "Country": "DE", 
 "StreetName": "Straße", 
 "PostalCode": "81371"
 }]
}

###
GET http://localhost:4004/odata/v4/admin/BusinessPartner(BusinessPartner='MAXSTR')?$expand=addresses
Content-Type: application/json
Authorization: Basic bp-admin 123

###

GET http://localhost:4004/odata/v4/admin/BusinessPartnerVerification?$expand=addresses&$filter=BusinessPartner eq 'TEST12'
Content-Type: application/json


### 

PATCH http://localhost:4004/odata/v4/businesspartner-dest/A_BusinessPartner('TEST12')
Content-Type: application/json

{ "BusinessPartner": "TEST11",
 "BusinessPartnerIsBlocked": false,
 "to_BusinessPartnerAddress": [{"BusinessPartner": "TEST11",
 "AddressID": "HALLO",
 "HouseNumber": "2",
 "CityName": "Munich",
 "Country": "DE", 
 "StreetName": "Straße", 
 "PostalCode": "81371"
 }]
}
